### ISSUE TITLE
__LINE__ becomes wrong value after heredoc start

### ISSUE THREAD

**Issue by mvz** [seattlerb/ruby_parser#291] opened 2019-04-14 17:48 UTC
```ruby
[11] pry(main)> ENV['VERBOSE'] = 'true'
=> "true"
[12] pry(main)> RubyParser.for_current_ruby.parse("bar <<TXT, __LINE__\nfoo\nTXT")
=> s(:call, nil, :bar, s(:str, "foo\n").line(1), s(:lit, 3).line(3)).line(1)
```

`__LINE__` is rendered as `s(:lit, 3)`, but it is on line 1.

**Comment by zenspider** [comment] 2019-04-14 22:31
Ditto to #292. This is especially true for any code that follows the heredoc start.

**Comment by zenspider** [comment] 2019-04-17 11:03
I'm gonna close this as it really is just a duplicate of #292.

**Closed by zenspider** 2019-04-17 11:03 UTC
