### ISSUE TITLE
Incorrect handling of keyword after newline after kwarg in paren-less def

### ISSUE THREAD

**Issue by whitequark** [seattlerb/ruby_parser#160] opened 2014-10-03 14:21 UTC
I.e.:

```
[2] pry(main)> Ruby21Parser.new.parse("def a b:\nreturn\nend")
=> s(:defn, :a, s(:args, s(:kwarg, :b, s(:return))), s(:nil))
```

Expected result:

```
=> s(:defn, :a, s(:args, s(:kwarg, :b)), s(:return))
```

Note that this has been fixed in 2.1.2 (or 2.1.3, I don't remember exactly), in 2.1.1 and earlier the behavior is as your current.

Have fun.

**Comment by zenspider** [comment] 2019-03-25 23:21
This was a duplicate of another bug I just closed. Closing.

**Closed by zenspider** 2019-03-25 23:21 UTC
