### ISSUE TITLE
Ruby 3.0 "endless" methods are not parsed

### ISSUE THREAD

**Issue by mildred** [seattlerb/ruby_parser#320] opened 2021-07-07 12:19 UTC
https://rubyreferences.github.io/rubychanges/3.0.html#endless-method-definition

The minimal source below fails to parse:

```rb
def a = :a
```

**Comment by zenspider** [comment] 2021-08-04 09:45
confirmed

**Comment by davidcarlin-ap** [comment] 2021-09-16 03:17
This is a bit of a problem for me. Do you have any idea of when this will be fixed? Thanks

**Comment by davidcarlin-ap** [comment] 2021-09-17 03:59
It looks like this was fixed in this commit https://github.com/seattlerb/ruby_parser/commit/b877e46d5ac5b2fcd94e0d7ff118bbdbd6e34e04
Can we get a new release for this please ? ❤️

**Comment by presidentbeef** [comment] 2021-09-17 21:44
Yes, I'm planning a small bug fix release in the next couple weeks. I can update ruby_parser then.

**Closed** 2021-10-10 00:49 UTC
