### ISSUE TITLE
Ruby 3.0 argument forwarding does not parse

### ISSUE THREAD

**Issue by mildred** [seattlerb/ruby_parser#321] opened 2021-07-07 12:21 UTC
https://rubyreferences.github.io/rubychanges/3.0.html#arguments-forwarding--supports-leading-arguments

The following minimal ruby example do not parse:

```rb
def a(...)
  b(...)
end
```

**Comment by danleyden** [comment] 2021-07-31 09:43
I believe this is a duplicate of #311

**Comment by zenspider** [comment] 2021-08-04 09:44
Dupe and fixed

**Closed by zenspider** 2021-08-04 09:44 UTC
